version: '3.7'
services:
    db:
        image: 'postgis/postgis:12-3.3'
        container_name: gogame.db
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=gogame_postgres
            - POSTGRES_PASSWORD=click123
            - POSTGRES_DB=gogame_db
        volumes:
            - 'gogame_api_postgres_data:/var/lib/postgresql'

    redis:
        container_name: gogame.redis
        image: 'bitnami/redis:6.0.16'
        ports:
            - 6379:6379
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - 'gogame_api_redis_data:/bitnami'

networks:
    nest:
        driver: bridge

volumes:
    gogame_api_postgres_data:
        external: true
    gogame_api_redis_data:
        external: true
