version: '3.7'
services:
    db:
        image: 'kartoza/postgis:14-3.2'
        container_name: gogame.db
        ports:
            - DOCKER_POSTGRES_PORT:5432
        environment:
            - POSTGRES_USER=gogame_postgres_dev
            - POSTGRES_PASS=click123
            - POSTGRES_DB=gogame_db_dev
        volumes:
            - 'gogame_api_postgres_data:/var/lib/postgresql'

    redis:
        container_name: gogame.redis
        image: 'bitnami/redis:6.0.16'
        ports:
            - DOCKER_REDIS_PORT:6379
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - 'gogame_api_redis_data:/bitnami'

volumes:
    gogame_api_postgres_data:
        external: true
    gogame_api_redis_data:
        external: true
